### ISSUE TITLE
widget content disappears when using theme customizer

### ISSUE THREAD

**Issue by offordscott** [Pressed-Solutions/IT-ROI-nice-login-widget#1]
I'm not sure if this has been addressed yet, but it seems like the plugin author has abandoned the plugin ( https://wordpress.org/plugins/nice-login-register-widget/ ). It hasn't been updated in over a year.

I would love it if someone could fix the issue where the widget content disappears when using theme customizer to configure the widget.

CC: @macbookandrew @pressedsolutions

**Comment by macbookandrew** [comment]
That would be nice, but unfortunately this is the wrong place to ask. Hope the developer can help you in the WordPress forums.

**Comment by offordscott** [comment]
I'm hoping to revive this plugin. I don't think the original developer is interested. I guess if you aren't interested in collaborating on it, I'll fork it.

**Comment by macbookandrew** [comment]
@offordscott Help yourself, but this repo was mainly a backup for a hacked copy of the plugin for a previous client. Sorry :disappointed: 

My guess is that the original developer used it to build his premium product and now maintains that instead: http://superplug.in/login-widget-pro/
